version: "3.7"
services:
  gurkbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gurkbot
    init: true

    restart: always

    environment:
      - TOKEN
      - PREFIX
      - CHANNEL_DEVLOG
      - CHANNEL_DEVALERTS
      - CHANNEL_DEV_GURKBOT
      - CHANNEL_DEV_REAGURK
      - CHANNEL_DEV_GURKLANG
      - CHANNEL_DEV_BRANDING
      - CHANNEL_LOGS

    volumes:
      - .:/bot
